### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by speaker-60** [WesternGamer/CustomLoadingBackgrounds#3]
Id like the background  overlay of the menu when ingame to be different to the one on the main menu
That overlay texture the game uses

Im making a whole new theme https://cdn.discordapp.com/attachments/736560503035527209/952726244296908850/unknown.png

The ui elements are part of the overlay texture, when ingame the ad and update stuff on the right isnt there so the ui elements iv added are left floating so ideally i want to have the ingame menu overlay be a different texture to the main menu

**Comment by speaker-60** [comment]
So you have a second overlay that can be enabled that overlays over the first, this is good i can use it to move some details over that just appear in the main menu. I cant find what this overlay texture is?

Could you expose the overlay texture path in the config so i can set custom overlays for each use
one for the main menu one for the second overlay on the main menu and a new unique one for loading screens

**Comment by WesternGamer** [comment]
Added in 1.5 update.
